# Configuration for CreativeControl written by XorNick. "chatcontrol.admin" to override what's listed here.
# Written with love <3


#==============================
#         Protection
#==============================

## Toggle whether or not you'd like to block the following actions triggered by players in creative.
block:
  pvp: true
  dropItems: true
  chests: true
  itemPickup: true
  blockBreak: true
  spawnEggs: true

## Enable / disable what blocks you are allowed to place.
block-place-blacklist:
  enabled: true
  ### Should be the numeral IDs for blocks. Use this for reference: http://minecraft-ids.grahamedgecombe.com/
  ### Blocks placing diamond blocks by default.
  blacklist:
    - 57

## Enable / disable what blocks you are allowed to break.
block-break-blacklist:
  enabled: true
    ### Should be the numeral IDs for blocks. Use this for reference: http://minecraft-ids.grahamedgecombe.com/
    ### Blocks breaking diamond blocks by default.
  blacklist:
    - 57


#==============================
#         Storage
#==============================

## Determines whether or not you'd like the player's survival inventory to be stored and cleared while in Creative,
## then swapped back when they go back to Survival.
inventoryStorage:
  enabled: false